/** @const */
const IDS = {
    MEDIA_URL_INPUT: "u",
    LOAD_BUTTON: "l",
    DOWNLOAD_BUTTON: "d",
    DOWNLOAD_DIALOG: "g",
    DOWNLOAD_DIALOG_DOMAIN: "c",
    DOWNLOAD_DIALOG_PROCEED_BUTTON: "p",
    DOWNLOAD_DIALOG_CANCEL: "e",
    VIDEO_PLAYER: "v",
    IMAGE_VIEWER: "i",
    AUDIO_PLAYER: "h",
    ERROR_MESSAGE: "z",
}
